from enum import Enum


class UserStatus(str, Enum):
    """Status of a user account."""
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"
    PENDING_VERIFICATION = "PENDING_VERIFICATION"


class OrganizationStatus(str, Enum):
    """Status of an organization."""
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"


class AuditAction(str, Enum):
    """Types of actions logged in the audit trail."""
    CREATE = "CREATE"
    READ = "READ"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    FAILED_LOGIN = "FAILED_LOGIN"
    PASSWORD_RESET = "PASSWORD_RESET"
    ROLE_ASSIGNED = "ROLE_ASSIGNED"


class EntityType(str, Enum):
    """Entities that can be audited."""
    USER = "USER"
    ORGANIZATION = "ORGANIZATION"
    ROLE = "ROLE"
    PERMISSION = "PERMISSION"
    FACTORY = "FACTORY"
    DEPARTMENT = "DEPARTMENT"
    TEAM = "TEAM"
    MACHINE = "MACHINE"
    COMPONENT = "COMPONENT"
    PART = "PART"
    DOCUMENT = "DOCUMENT"
    WORK_ORDER = "WORK_ORDER"
    SENSOR = "SENSOR"
    PREDICTION = "PREDICTION"
    COMPLIANCE = "COMPLIANCE"
    VISION = "VISION"

class IndustrySector(str, Enum):
    AUTOMOTIVE = "AUTOMOTIVE"
    AEROSPACE = "AEROSPACE"
    MANUFACTURING = "MANUFACTURING"
    PHARMACEUTICAL = "PHARMACEUTICAL"
    ELECTRONICS = "ELECTRONICS"
    OTHER = "OTHER"

class OperationalStatus(str, Enum):
    ACTIVE = "ACTIVE"
    MAINTENANCE = "MAINTENANCE"
    INACTIVE = "INACTIVE"
    CLOSED = "CLOSED"

class CompanySize(str, Enum):
    SMALL = "SMALL"       # 1-50
    MEDIUM = "MEDIUM"     # 51-200
    LARGE = "LARGE"       # 201-1000
    ENTERPRISE = "ENTERPRISE" # 1000+

class FactorySize(str, Enum):
    SMALL = "SMALL"
    MEDIUM = "MEDIUM"
    LARGE = "LARGE"

class OperationalCriticality(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class ProductionType(str, Enum):
    DISCRETE = "DISCRETE"
    PROCESS = "PROCESS"
    BATCH = "BATCH"
    CONTINUOUS = "CONTINUOUS"
    MIXED = "MIXED"

class DepartmentType(str, Enum):
    MECHANICAL = "MECHANICAL"
    ELECTRICAL = "ELECTRICAL"
    INSTRUMENTATION = "INSTRUMENTATION"
    PRODUCTION = "PRODUCTION"
    OPERATIONS = "OPERATIONS"
    MAINTENANCE = "MAINTENANCE"
    SAFETY = "SAFETY"
    QUALITY = "QUALITY"
    INSPECTION = "INSPECTION"
    ENGINEERING = "ENGINEERING"
    IT_AUTOMATION = "IT_AUTOMATION"
    CUSTOM = "CUSTOM"

class RelationshipType(str, Enum):
    CONTAINS = "CONTAINS"
    USES = "USES"
    LOCATED_IN = "LOCATED_IN"
    BELONGS_TO = "BELONGS_TO"
    INSTALLED_AT = "INSTALLED_AT"
    MANUFACTURED_BY = "MANUFACTURED_BY"
    HAS_DOCUMENT = "HAS_DOCUMENT"
    HAS_MANUAL = "HAS_MANUAL"
    HAS_SENSOR = "HAS_SENSOR"
    HAS_FAILURE = "HAS_FAILURE"
    HAS_MAINTENANCE = "HAS_MAINTENANCE"
    CAUSED_BY = "CAUSED_BY"
    RESOLVED_BY = "RESOLVED_BY"
    SIMILAR_TO = "SIMILAR_TO"
    REFERENCES = "REFERENCES"

class RiskLevel(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

class RiskCategory(str, Enum):
    SAFETY = "SAFETY"
    PRODUCTION = "PRODUCTION"
    FINANCIAL = "FINANCIAL"
    ENVIRONMENTAL = "ENVIRONMENTAL"
    COMPLIANCE = "COMPLIANCE"

class DocumentType(str, Enum):
    ENGINEERING_DRAWING = "ENGINEERING_DRAWING"
    PID_DIAGRAM = "PID_DIAGRAM"
    MAINTENANCE_MANUAL = "MAINTENANCE_MANUAL"
    SOP = "SOP"
    INSPECTION_REPORT = "INSPECTION_REPORT"
    WORK_ORDER = "WORK_ORDER"
    SAFETY_DOCUMENT = "SAFETY_DOCUMENT"
    INCIDENT_REPORT = "INCIDENT_REPORT"
    TRAINING_DOCUMENT = "TRAINING_DOCUMENT"
    OTHER = "OTHER"

class ProcessingStatus(str, Enum):
    UPLOADED = "UPLOADED"
    VALIDATING = "VALIDATING"
    PROCESSING = "PROCESSING"
    OCR_PROCESSING = "OCR_PROCESSING"
    EXTRACTING = "EXTRACTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class ExtractionType(str, Enum):
    TEXT = "TEXT"
    TABLE = "TABLE"
    IMAGE = "IMAGE"
    METADATA = "METADATA"

class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    
class JobType(str, Enum):
    FULL_EXTRACTION = "FULL_EXTRACTION"
    OCR_ONLY = "OCR_ONLY"
    TABLE_EXTRACTION = "TABLE_EXTRACTION"

class ExtractedEntityType(str, Enum):
    MACHINE = "MACHINE"
    COMPONENT = "COMPONENT"
    PART = "PART"
    PARAMETER = "PARAMETER"
    FAILURE = "FAILURE"
    MAINTENANCE_ACTION = "MAINTENANCE_ACTION"
    SAFETY_RULE = "SAFETY_RULE"
    PERSON = "PERSON"
    LOCATION = "LOCATION"
    DOCUMENT_REFERENCE = "DOCUMENT_REFERENCE"

class ScopeType(str, Enum):
    GLOBAL = "GLOBAL"
    ORGANIZATION = "ORGANIZATION"
    FACTORY = "FACTORY"
    DEPARTMENT = "DEPARTMENT"

class FeedbackType(str, Enum):
    HELPFUL = "HELPFUL"
    INCORRECT = "INCORRECT"
    ALTERNATIVE_SOLUTION = "ALTERNATIVE_SOLUTION"
    ADDITIONAL_INFORMATION = "ADDITIONAL_INFORMATION"
    CORRECTION = "CORRECTION"
    NEW_FAILURE_PATTERN = "NEW_FAILURE_PATTERN"
    NEW_MAINTENANCE_PROCEDURE = "NEW_MAINTENANCE_PROCEDURE"
    SAFETY_IMPROVEMENT = "SAFETY_IMPROVEMENT"

class SolutionStatus(str, Enum):
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ARCHIVED = "ARCHIVED"

class MaintenanceType(str, Enum):
    PREVENTIVE = "PREVENTIVE"
    CORRECTIVE = "CORRECTIVE"
    EMERGENCY = "EMERGENCY"
    INSPECTION = "INSPECTION"
    CALIBRATION = "CALIBRATION"
    REPLACEMENT = "REPLACEMENT"
    OVERHAUL = "OVERHAUL"

class MaintenanceStatus(str, Enum):
    SCHEDULED = "SCHEDULED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"

class FailureType(str, Enum):
    OVERHEATING = "OVERHEATING"
    VIBRATION = "VIBRATION"
    LEAKAGE = "LEAKAGE"
    CORROSION = "CORROSION"
    ELECTRICAL = "ELECTRICAL"
    MECHANICAL = "MECHANICAL"
    PRESSURE = "PRESSURE"
    SENSOR = "SENSOR"
    UNKNOWN = "UNKNOWN"

class FailureSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class FindingStatus(str, Enum):
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"

class FindingSeverity(str, Enum):
    MINOR = "MINOR"
    MAJOR = "MAJOR"
    CRITICAL = "CRITICAL"

class CorrectiveActionStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    VERIFIED = "VERIFIED"

class MediaType(str, Enum):
    IMAGE = "IMAGE"
    VIDEO = "VIDEO"

class AnalysisStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"

class DefectType(str, Enum):
    RUST = "RUST"
    CORROSION = "CORROSION"
    LEAKAGE = "LEAKAGE"
    CRACK = "CRACK"
    WEAR = "WEAR"
    SMOKE = "SMOKE"
    OVERHEATING = "OVERHEATING"
    MISSING_COMPONENT = "MISSING_COMPONENT"
    LOOSE_CONNECTION = "LOOSE_CONNECTION"
    ABNORMAL_CONDITION = "ABNORMAL_CONDITION"

class SensorType(str, Enum):
    TEMPERATURE = "TEMPERATURE"
    PRESSURE = "PRESSURE"
    VIBRATION = "VIBRATION"
    HUMIDITY = "HUMIDITY"
    FLOW = "FLOW"
    CURRENT = "CURRENT"
    VOLTAGE = "VOLTAGE"
    ENERGY = "ENERGY"
    SPEED = "SPEED"

class DeviceStatus(str, Enum):
    ONLINE = "ONLINE"
    OFFLINE = "OFFLINE"
    MAINTENANCE = "MAINTENANCE"
    ERROR = "ERROR"

class AlertStatus(str, Enum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    RESOLVED = "RESOLVED"

class FailurePredictionType(str, Enum):
    BEARING = "BEARING"
    MOTOR = "MOTOR"
    PUMP = "PUMP"
    VALVE = "VALVE"
    ELECTRICAL = "ELECTRICAL"
    OVERHEATING = "OVERHEATING"
    LEAKAGE = "LEAKAGE"

class ActionRecommendation(str, Enum):
    REPAIR = "REPAIR"
    MONITOR = "MONITOR"
    REPLACE = "REPLACE"
    SHUTDOWN = "SHUTDOWN"

class MaintenanceRecommendationPriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class ActivityType(str, Enum):
    LOGIN = "LOGIN"
    QA_ASKED = "QA_ASKED"
    DOCUMENT_UPLOAD = "DOCUMENT_UPLOAD"
    MAINTENANCE_ACTION = "MAINTENANCE_ACTION"
    EXPORT_REPORT = "EXPORT_REPORT"

class ReportType(str, Enum):
    DAILY = "DAILY"
    WEEKLY = "WEEKLY"
    MONTHLY = "MONTHLY"
    CUSTOM = "CUSTOM"

class ExportFormat(str, Enum):
    PDF = "PDF"
    EXCEL = "EXCEL"
    CSV = "CSV"
    JSON = "JSON"

class WorkOrderStatus(str, Enum):
    DRAFT = "DRAFT"
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    ACCEPTED = "ACCEPTED"
    IN_PROGRESS = "IN_PROGRESS"
    WAITING_FOR_PARTS = "WAITING_FOR_PARTS"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    COMPLETED = "COMPLETED"
    VERIFIED = "VERIFIED"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"

class WorkOrderPriority(str, Enum):
    EMERGENCY = "EMERGENCY"
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"

class ConnectorType(str, Enum):
    ERP = "ERP"
    CMMS = "CMMS"
    MES = "MES"
    SCADA = "SCADA"
    PLC = "PLC"
    PROTOCOL = "PROTOCOL"
    WEBHOOK = "WEBHOOK"

class ConnectorStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    ERROR = "ERROR"

class SyncStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"

class ModelStatus(str, Enum):
    DRAFT = "DRAFT"
    STAGING = "STAGING"
    PRODUCTION = "PRODUCTION"
    ARCHIVED = "ARCHIVED"

class SecurityEventType(str, Enum):
    LOGIN_FAILED = "LOGIN_FAILED"
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS"
    PROMPT_INJECTION_ATTEMPT = "PROMPT_INJECTION_ATTEMPT"
    SUSPICIOUS_FILE_UPLOAD = "SUSPICIOUS_FILE_UPLOAD"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"

class AgentType(str, Enum):
    MAINTENANCE = "MAINTENANCE"
    RCA = "RCA"
    PREDICTIVE = "PREDICTIVE"
    DOCUMENT = "DOCUMENT"
    VISION = "VISION"
    COMPLIANCE = "COMPLIANCE"
    SAFETY = "SAFETY"
    IOT = "IOT"
    WORKFLOW = "WORKFLOW"
    KNOWLEDGE_GRAPH = "KNOWLEDGE_GRAPH"
    ORCHESTRATOR = "ORCHESTRATOR"

class IntentType(str, Enum):
    MAINTENANCE_PLANNING = "MAINTENANCE_PLANNING"
    ROOT_CAUSE = "ROOT_CAUSE"
    RISK_ASSESSMENT = "RISK_ASSESSMENT"
    GENERAL_QUERY = "GENERAL_QUERY"

class MachineStatus(str, Enum):
    OPERATIONAL = "OPERATIONAL"
    MAINTENANCE = "MAINTENANCE"
    STOPPED = "STOPPED"
    FAILED = "FAILED"
    RETIRED = "RETIRED"

class AssetCriticality(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

class ConditionStatus(str, Enum):
    NEW = "NEW"
    GOOD = "GOOD"
    FAIR = "FAIR"
    POOR = "POOR"
    CRITICAL = "CRITICAL"
